name: Simplecov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  simplecov:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Install library for postgres
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: bundle install
      - name: Setup Database
        run: |
          bin/rails db:create
          bundle exec rails db:create
          bundle exec rails db:migrate
        env:
          POSTGRES_DB: proyecto-Testing_development
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
      - name: Run simplecov
        run:
          bundle exec rails test
