name: Simplecov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  simplecov:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          DB_PASSWORD: postgres
          DB_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Get sqlite for Rails test projects
        run: sudo apt-get install libsqlite3-dev
        
      - name: Install library for postgres
        run: sudo apt-get install libpq-dev
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Set up db
        run:
          bundle exec rails db:migrate RAILS_ENV=test
        
      - name: Run simplecov
        run:
          bundle exec rails test
